name: generate_readme
on: [push, pull_request]
jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
      run: |
        go install github.com/tjgurwara99/godocmd@v0.1.1
        ls