# https://github.com/golangci/golangci-lint
name: golangci-lint
on: [push, pull_request]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v2.4
      - run: echo "/home/runner/golangci-lint-2.4.0-linux-amd64" >> $GITHUB_PATH
      - run: go version ; golangci-lint --version  # Fix the following and remove || true
      # - run: golangci-lint run --no-config . || true
      - run: golangci-lint run --no-config ./...
      - run: shopt -s globstar && golangci-lint run --no-config **/*.go || true
