# https://github.com/golangci/golangci-lint
name: golangci-lint
on: [push, pull_request]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
    - uses: actions/checkout@v1
    - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.21.0
    - run: |
        ./bin/golangci-lint --version
        ./bin/golangci-lint run --no-config
